-- local cmp = {
-- 	CmpItemAbbrMatch = { fg = C.blue_3 },
-- 	CmpItemAbbrMatchFuzzy = { fg = C.blue_3 },
-- 	CmpItemKindVariable = { fg = C.light_blue },
-- 	CmpItemKindInterface = { fg = C.light_blue },
-- 	CmpItemKindText = { fg = C.light_blue },
-- 	CmpItemKindFunction = { fg = C.purple },
-- 	CmpItemKindMethod = { fg = C.purple },
-- 	CmpItemKindKeyword = { fg = C.white_3 },
-- 	CmpItemKindProperty = { fg = C.white_3 },
-- 	CmpItemKindUnit = { fg = C.purple },
-- }

local cmp = {
	CmpItemAbbr = { fg = C.fg },
	CmpItemAbbrDeprecated = { fg = C.fg },
	CmpItemAbbrMatch = { fg = C.cyan },
	CmpItemAbbrMatchFuzzy = { fg = C.cyan },

	CmpItemKindDefault = { fg = C.purple },
	CmpItemKindClass = { fg = C.yellow },
	CmpItemKindColor = { fg = C.green },
	CmpItemKindConstant = { fg = C.orange },
	CmpItemKindConstructor = { fg = C.blue },
	CmpItemKindEnum = { fg = C.purple },
	CmpItemKindEnumMember = { fg = C.yellow },
	CmpItemKindEvent = { fg = C.yellow },
	CmpItemKindField = { fg = C.purple },
	CmpItemKindFile = { fg = C.blue },
	CmpItemKindFolder = { fg = C.orange },
	CmpItemKindFunction = { fg = C.blue },
	CmpItemKindInterface = { fg = C.green },
	CmpItemKindKeyword = { fg = C.cyan },
	CmpItemKindMethod = { fg = C.blue },
	CmpItemKindModule = { fg = C.orange },
	CmpItemKindOperator = { fg = C.red },
	CmpItemKindProperty = { fg = C.cyan },
	CmpItemKindReference = { fg = C.orange },
	CmpItemKindSnippet = { fg = C.red },
	CmpItemKindStruct = { fg = C.purple },
	CmpItemKindText = { fg = C.grey_1 },
	CmpItemKindTypeParameter = { fg = C.red },
	CmpItemKindUnit = { fg = C.green },
	CmpItemKindValue = { fg = C.orange },
	CmpItemKindVariable = { fg = C.purple },
}

return cmp
