-- local cmp = {
-- 	CmpItemAbbrMatch = { fg = C.blue_3 },
-- 	CmpItemAbbrMatchFuzzy = { fg = C.blue_3 },
-- 	CmpItemKindVariable = { fg = C.light_blue },
-- 	CmpItemKindInterface = { fg = C.light_blue },
-- 	CmpItemKindText = { fg = C.light_blue },
-- 	CmpItemKindFunction = { fg = C.purple },
-- 	CmpItemKindMethod = { fg = C.purple },
-- 	CmpItemKindKeyword = { fg = C.white_3 },
-- 	CmpItemKindProperty = { fg = C.white_3 },
-- 	CmpItemKindUnit = { fg = C.purple },
-- }

local cmp = {
	CmpItemAbbr = { fg = C.fg },
	CmpItemAbbrDeprecated = { C.fg },
	CmpItemAbbrMatch = { C.cyan },
	CmpItemAbbrMatchFuzzy = { fg = C.cyan },
	CmpItemMenu = { C.grey_1 },

	CmpItemKindDefault = { C.purple },
	CmpItemKindClass = { C.yellow },
	CmpItemKindColor = { C.green },
	CmpItemKindConstant = { C.orange },
	CmpItemKindConstructor = { C.blue },
	CmpItemKindEnum = { C.purple },
	CmpItemKindEnumMember = { C.yellow },
	CmpItemKindEvent = { C.yellow },
	CmpItemKindField = { C.purple },
	CmpItemKindFile = { C.blue },
	CmpItemKindFolder = { C.orange },
	CmpItemKindFunction = { C.blue },
	CmpItemKindInterface = { C.green },
	CmpItemKindKeyword = { C.cyan },
	CmpItemKindMethod = { C.blue },
	CmpItemKindModule = { C.orange },
	CmpItemKindOperator = { C.red },
	CmpItemKindProperty = { C.cyan },
	CmpItemKindReference = { C.orange },
	CmpItemKindSnippet = { C.red },
	CmpItemKindStruct = { C.purple },
	CmpItemKindText = { C.grey_1 },
	CmpItemKindTypeParameter = { C.red },
	CmpItemKindUnit = { C.green },
	CmpItemKindValue = { C.orange },
	CmpItemKindVariable = { C.purple },
}

return cmp
