local variants = require("astron.colors")
print(vim.inspect(variants))
local conf = require("astron.config").config
print(vim.inspect(conf))
local c = variants[conf.variant]
print(vim.inspect(c))
local utils = require("astron.utils")
local M = {}

local set_groups = function()
  local groups = {
		-- Italic stuff
		Comment = { fg = c.grey_2, bg = c.none, style = conf.comment_style },
		Conditional = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		Keyword = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		Repeat = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		Function = { fg = c.blue, bg = c.none, style = conf.function_style },

		-- Basic stuff
		Normal = { fg = c.fg, bg = c.bg },
		Boolean = { fg = c.orange, bg = c.none, style = conf.boolean_style},
		Constant = { fg = c.yellow, bg = c.none },
		String = { fg = c.green, bg = c.none },
		Character = { fg = c.green, bg = c.none },
		Number = { fg = c.orange, bg = c.none },
		Float = { fg = c.yellow, bg = c.none },
		Identifier = { fg = c.blue, bg = c.none },
		Statement = { fg = c.purple, bg = c.none },
		Label = { fg = c.blue, bg = c.none },
		Operator = { fg = c.purple, bg = c.none },
		Exception = { fg = c.purple, bg = c.none },
		Preproc = { fg = c.yellow, bg = c.none },
		Include = { fg = c.purple, bg = c.none },
		Define = { fg = c.purple, bg = c.none },
		Title = { fg = c.cyan, bg = c.none },
		Macro = { fg = c.purple, bg = c.none },
		PreCondit = { fg = c.blue, bg = c.none },
		Type = { fg = c.blue, bg = c.none },
		StorageClass = { fg = c.blue, bg = c.none },
		Structure = { fg = c.yellow, bg = c.none },
		Typedef = { fg = c.yellow, bg = c.none },
		Special = { fg = c.blue, bg = c.none },
		SpecialComment = { fg = c.grey, bg = c.none },
		Error = { fg = c.red, bg = c.none },
		Todo = { fg = c.purple, bg = c.none },
		Underlined = { fg = c.cyan, bg = c.none },
		Cursor = { fg = c.none, bg = c.none },
		ColorColumn = { fg = c.none, bg = c.grey_4 },
		CursorLineNr = { fg = c.fg, bg = c.none },
		Conceal = { fg = c.grey, bg = c.none },
		CursorColumn = { fg = c.none, bg = c.grey_4 },
		CursorLine = { fg = c.none, bg = c.grey_8 },
		Directory = { fg = c.blue, bg = c.none },
		DiffAdd = { fg = c.grey_3, bg = c.green },
		DiffChange = { fg = c.yellow, bg = c.none },
		DiffDelete = { fg = c.grey_3, bg = c.red },
		DiffText = { fg = c.grey_3, bg = c.yellow },
		ErrorMsg = { fg = c.red, bg = c.none },
		VertSplit = { fg = c.black, bg = c.none },
		Folded = { fg = c.grey, bg = c.none },
		FoldColumn = { fg = c.none, bg = c.none },
		IncSearch = { fg = c.blue_1, bg = c.grey },
		LineNr = { fg = c.grey_2, bg = c.none },
		NonText = { fg = c.grey_1, bg = c.none },
		Pmenu = { fg = c.fg, bg = c.black_1 },
		PmenuSel = { fg = c.none, bg = c.grey_4 },
		PmenuSbar = { fg = c.none, bg = c.grey_3 },
		PmenuThumb = { fg = c.none, bg = c.fg },
		Question = { fg = c.purple, bg = c.none },
		QuickFixLine = { fg = c.grey_3, bg = c.yellow },
		Search = { fg = c.grey_3, bg = c.yellow },
		SignColumn = { fg = c.bg, bg = c.bg },
		SpecialKey = { fg = c.grey_1, bg = c.none },
		SpellBad = { fg = c.red, bg = c.none },
		SpellCap = { fg = c.yellow, bg = c.none },
		SpellLocal = { fg = c.yellow, bg = c.none },
		SpellRare = { fg = c.yellow, bg = c.none },
		StatusLine = { fg = c.fg, bg = c.bg },
		StatusLineNC = { fg = c.grey, bg = c.none },
		StatusLineTerm = { fg = c.fg, bg = c.grey_4 },
		StatusLineTermNC = { fg = c.grey_4, bg = c.none },
		TabLine = { fg = c.grey, bg = c.none },
		TabLineSel = { fg = c.fg, bg = c.none },
		TabLineFill = { fg = c.none, bg = c.grey_3 },
		Terminal = { fg = c.fg, bg = c.grey_3 },
		Visual = { fg = c.none, bg = c.grey_5 },
		VisualNOS = { fg = c.grey_5, bg = c.none },
		WarningMsg = { fg = c.yellow, bg = c.none },
		WildMenu = { fg = c.grey_3, bg = c.blue },
		EndOfBuffer = { fg = c.bg, bg = c.none },
		FloatBorder = { bg = c.none },
		MatchParen = { fg = c.none, bg = c.grey_5 },

		  -- Italics stuff
		  TSComment = { fg = c.grey_2, bg = c.none, style = conf.comment_style },
		  TSBoolean = { fg = c.orange, bg = c.none, style = conf.boolean_style },
		  TSConditional = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		  TSKeyword = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		  TSKeywordReturn = { fg = c.purple, style = conf.keyword_style },
		  TSRepeat = { fg = c.purple, bg = c.none, style = conf.keyword_style },
		  TSFunction = { fg = c.blue, bg = c.none, style = conf.function_style },
		  TSKeywordFunction = { fg = c.blue, bg = c.none, conf.function_style },
		  TSFuncBuiltin = { fg = c.blue, bg = c.bgnone, style = conf.function_style },
		  TSMethod = { fg = c.blue, bg = c.none, style = conf.function_style },

		  -- Basic stuff
		  TSError = { fg = c.red, bg = c.none },
		  TSPunctDelimiter = { fg = c.fg, bg = c.none },
		  TSPunctBracket = { fg = c.fg, bg = c.none },
		  TSPunctSpecial = { fg = c.fg, bg = c.none },
		  TSConstant = { fg = c.yellow, bg = c.none },
		  TSConstBuiltin = { fg = c.orange, bg = c.none },
		  TSConstMacro = { fg = c.red, bg = c.none },
		  TSStringRegex = { fg = c.green, bg = c.none },
		  TSString = { fg = c.green, bg = c.none },
		  TSStringEscap = { fg = c.red, bg = c.none },
		  TSCharacter = { fg = c.green, bg = c.none },
		  TSNumber = { fg = c.orange, bg = c.none },
		  TSFloat = { fg = c.green, bg = c.none },
		  TSAnnotation = { fg = c.yellow, bg = c.none },
		  TSAttribute = { fg = c.red, bg = c.none },
		  TSNamespace = { fg = c.purple, bg = c.none },
		  TSFuncMacro = { fg = c.yellow, bg = c.none },
		  TSParameter = { fg = c.red, bg = c.none },
		  TSParameterReference = { fg = c.cyan, bg = c.none },
		  TSField = { fg = c.red, bg = c.none },
		  TSProperty = { fg = c.yellow, bg = c.none },
		  TSConstructor = { fg = c.yellow, bg = c.none },
		  TSLabel = { fg = c.blue, bg = c.none },
		  TSKeywordOperator = { fg = c.purple, bg = c.none },
		  TSOperator = { fg = c.cyan, bg = c.none },
		  TSException = { fg = c.purple, bg = c.none },
		  TSType = { fg = c.blue, bg = c.none },
		  TSTypeBuiltin = { fg = c.blue, bg = c.none },
		  TSStructure = { fg = c.purple, bg = c.none },
		  TSInclude = { fg = c.purple, bg = c.none },
		  TSVariable = { fg = c.red, bg = c.none, style = conf.variable_style },
		  TSVariableBuiltin = { fg = c.yellow, bg = c.none, style = conf.variable_style },
		  TSText = { fg = c.fg, bg = c.none },
		  TSStrong = { fg = c.fg, bg = c.none },
		  TSEmphasis = { fg = c.fg, bg = c.none },
		  TSUnderline = { fg = c.fg, bg = c.none },
		  TSTitle = { fg = c.fg, bg = c.none },
		  TSLiteral = { fg = c.fg, bg = c.none },
		  TSURI = { fg = c.fg, bg = c.none },
		  TSTag = { fg = c.red, bg = c.none },
		  TSTagDelimiter = { fg = c.fg, bg = c.none },
		  rainbowcol1 = { fg = "Gold", bg = c.none },
		  rainbowcol2 = { fg = "Orchid", bg = c.none },
		  rainbowcol3 = { fg = "LightSkyBlue", bg = c.none },
		  rainbowcol4 = { fg = "Gold", bg = c.none },
		  rainbowcol5 = { fg = "Orchid", bg = c.none },
		  rainbowcol6 = { fg = "LightSkyBlue", bg = c.none },
		  rainbowcol7 = { fg = "Orchid", bg = c.none },


	  -- Telescope
	  TelescopeResultsTitle = { fg = c.green, style = "italic" },
	  TelescopePromptTitle = { fg = c.blue },
	  TelescopePreviewTitle = { fg = c.purple },
	  TelescopeResultsBorder = { fg = c.fg },
	  TelescopePromptBorder = { fg = c.fg },
	  TelescopePreviewBorder = { fg = c.fg },
	  TelescopeSelectionCaret = { fg = c.red },
	  TelescopeMatching = { fg = c.yellow },
	  TelescopeSelection = { bg = c.grey_5 },
	  TelescopeMultiSelection = { fg = c.blue },
	  TelescopeMultiIcon = { fg = c.blue },
	  TelescopeNormal = { fg = c.fg, bg = c.bg },
	  TelescopePreviewNormal = { fg = c.fg, bg = c.bg },
	  TelescopePromptNormal = { fg = c.fg, bg = c.bg },
	  TelescopeResultsNormal = { fg = c.fg, bg = c.bg },
	  TelescopeBorder = { fg = c.fg },
	  TelescopeTitle = { fg = c.fg },
	  TelescopePromptCounter = { fg = c.red },
	  TelescopePromptPrefix = { fg = c.blue },
	  TelescopePreviewLine = { fg = c.grey_5 },
	  TelescopePreviewMatch = { fg = c.yellow },
	  TelescopePreviewPipe = { fg = c.yellow },
	  TelescopePreviewCharDev = { fg = c.yellow },
	  TelescopePreviewDirectory = { fg = c.blue },
	  TelescopePreviewBlock = { fg = c.yellow },
	  TelescopePreviewLink = { fg = c.blue },
	  TelescopePreviewSocket = { fg = c.purple },
	  TelescopePreviewRead = { fg = c.yellow },
	  TelescopePreviewWrite = { fg = c.purple },
	  TelescopePreviewExecute = { fg = c.green },
	  TelescopePreviewHyphen = { fg = c.grey_1 },
	  TelescopePreviewSticky = { fg = c.blue },
	  TelescopePreviewSize = { fg = c.green },
	  TelescopePreviewUser = { fg = c.yellow },
	  TelescopePreviewGroup = { fg = c.yellow },
	  TelescopePreviewDate = { fg = c.blue },
	  TelescopePreviewMessage = { fg = c.fg },
	  TelescopePreviewMessageFillchar = { fg = c.fg },
	  TelescopeResultsClass = { fg = c.yellow },
	  TelescopeResultsConstant = { fg = c.yellow },
	  TelescopeResultsField = { fg = c.red },
	  TelescopeResultsFunction = { fg = c.blue },
	  TelescopeResultsMethod = { fg = c.blue },
	  TelescopeResultsOperator = { fg = c.cyan },
	  TelescopeResultsStruct = { fg = c.purple },
	  TelescopeResultsVariable = { fg = c.red },
	  TelescopeResultsLineNr = { fg = c.grey_1 },
	  TelescopeResultsIdentifier = { fg = c.blue },
	  TelescopeResultsNumber = { fg = c.orange },
	  TelescopeResultsComment = { fg = c.grey_2 },
	  TelescopeResultsSpecialComment = { fg = c.grey },
	  TelescopeResultsDiffChange = { fg = c.none, bg = c.yellow },
	  TelescopeResultsDiffAdd = { fg = c.none, bg = c.green },
	  TelescopeResultsDiffDelete = { fg = c.none, bg = c.red },
	  TelescopeResultsDiffUntracked = { fg = c.none, bg = c.grey_1 },

	  -- NvimTree
	  NvimTreeFolderIcon = { fg = c.blue },
	  NvimTreeExecFile = { fg = c.green },
	  NvimTreeOpenedFile = { fg = c.green },
	  NvimTreeRootFolder = { fg = c.fg },
	  NvimTreeEndOfBuffer = { fg = c.bg },
	  NvimTreeNormal = { bg = c.blue_2 },
	  NvimTreeNormalNC = { bg = c.blue_2 },
	  NvimTreeVertSplit = { fg = c.blue_2, bg = c.blue_2 },
	  NvimTreeImageFile = { fg = c.purple },
	  NvimTreeSymlink = { fg = c.cyan },
	  NvimTreeSpecialFile = { fg = c.yellow },
	  NvimTreeGitDeleted = { fg = c.red },
	  NvimTreeGitMerge = { fg = c.orange },
	  NvimTreeGitRenamed = { fg = c.purple },
	  NvimTreeGitStaged = { fg = c.green },
	  NvimTreeGitDirty = { fg = c.red },
	  NvimTreeGitNew = { fg = c.yellow },

	  -- VimWiki
	  VimwikiLink = { fg = c.cyan, bg = c.none },
	  VimwikiHeaderChar = { fg = c.grey, bg = c.none },
	  VimwikiHR = { fg = c.yellow, bg = c.none },
	  VimwikiList = { fg = c.orange, bg = c.orange },
	  VimwikiTag = { fg = c.orange, bg = c.orange },
	  VimwikiMarkers = { fg = c.grey, bg = c.none },
	  VimwikiHeader1 = { fg = c.orange, bg = c.none, style = "bold" },
	  VimwikiHeader2 = { fg = c.green, bg = c.none, style = "bold" },
	  VimwikiHeader3 = { fg = c.blue, bg = c.none, style = "bold" },
	  VimwikiHeader4 = { fg = c.cyan, bg = c.none, style = "bold" },
	  VimwikiHeader5 = { fg = c.yellow, bg = c.none, style = "bold" },
	  VimwikiHeader6 = { fg = c.purple, bg = c.none, style = "bold" },

	  -- IndentBlankLine
	  IndentBlanklineSpaceChar = { fg = c.grey_6, style = "nocombine" },
	  IndentBlanklineChar = { fg = c.grey_6, style = "nocombine" },
	  IndentBlanklineContextStart = { fg = c.grey_7, style = "underline" },
	  IndentBlanklineContextChar = { fg = c.grey_7, style = "nocombine" },
	  IndentBlanklineSpaceCharBlankline = { fg = c.grey_6, style = "nocombine" },

	  -- GitSigns
	  GitSignsAdd = { fg = c.green, bg = c.none },
	  GitSignsChange = { fg = c.orange_1, bg = c.none },
	  GitSignsDelete = { fg = c.red_1, bg = c.none },
	  MoreMsg = { fg = c.green, style = "bold" },
	  ModeMsg = { fg = c.grey, style = "bold" },

	  -- Dashboard
	  DashboardHeader = { fg = c.cyan },
	  DashboardShortcut = { fg = c.yellow },
	  DashboardFooter = { fg = c.purple, style = "italic" },
	  DashboardCenter = { fg = c.blue },

	  -- WhichKey
	  WhichKeyFloat = { fg = c.fg },
	  WhichKeyDesc = { fg = c.blue },
	  WhichKeyGroup = { fg = c.blue },

	  -- SymbolsOutline
	  FocusedSymbol = { fg = c.yellow, bg = c.none },

	  -- Markdown
		markdownH1 = { fg = c.red_1 },
		markdownH2 = { fg = c.red_1 },
		markdownH3 = { fg = c.red_1 },
		markdownH4 = { fg = c.red_1 },
		markdownH5 = { fg = c.red_1 },
		markdownH6 = { fg = c.red_1 },
		markdownHeadingDelimiter = { fg = c.red_1 },
		markdownHeadingRule = { fg = c.grey_3 },
		markdownBold = { fg = c.light_blue, style = "bold" },
		markdownItalic = { style = "italic" },
		markdownBlockquote = { fg = c.grey_1 },
		markdownBoldDelimiter = { fg = c.grey_1 },
		markdownCode = { fg = c.green },
		markdownCodeBlock = { fg = c.green },
		markdownCodeDelimeter = { fg = c.green },
		markdownId = { fg = c.purple },
		markdownIdDelimeter = { fg = c.purple },
		markdownIdDeclaration = { fg = c.blue },
		markdownUrl = { fg = c.cyan },
		markdownLinkDelimeter = { fg = c.purple },
		markdownLinkText = { fg = c.blue_3 },
		markdownListMarker = { fg = c.red },
		markdownOrderedListMarker = { fg = c.red },
		markdownRul = { fg = c.grey },

		-- LSP & LSP saga
		DiagnosticError = { fg = c.red_1 },
		DiagnosticWarn = { fg = c.orange_1 },
		DiagnosticInfo = { fg = c.white_2 },
		DiagnosticHint = { fg = c.yellow_1 },
		DiagnosticHeader = { fg = c.green_2 },
		DiagnosticUnderlineError = { style = "undercurl", sp = c.red_2 },
		DiagnosticUnderlineWarn = { style = "undercurl", sp = c.red_2 },
		DiagnosticUnderlineInfo = { style = "undercurl", sp = c.red_2 },
		DiagnosticUnderlineHint = { style = "undercurl", sp = c.red_2 },
		LspReferenceText = { fg = c.none, bg = c.grey_5 },
		LspReferenceRead = { fg = c.none, bg = c.grey_5 },
		LspReferenceWrite = { fg = c.none, bg = c.grey_5 },
		LspSagaDiagnosticBorder = { fg = c.white_1 },
		LspSagaSignatureHelpBorder = { fg = c.white_1 },
		LspSagaLspFinderBorder = { fg = c.white_1 },
		LspSagaCodeActionBorder = { fg = c.white_1 },
		LspSagaDefPreviewBorder = { fg = c.white_1 },
		LspSagaHoverBorder = { fg = c.white_1 },
		LspSagaRenameBorder = { fg = c.white_1 },
		LspSagaRenamePromptPrefix = { fg = c.white_1 },
		LspFloatWinBorder = { fg = c.white_1 },
		LspSagaDiagnosticTruncateLine = { fg = c.white_1 },
		LspSagaShTruncateLine = { fg = c.white_1 },
		LspSagaDocTruncateLine = { fg = c.white_1 },
		LspSagaCodeActionTruncateLine = { fg = c.white_1 },
		ProviderTruncateLine = { fg = c.white_1 },
		DiagnosticTruncateLine = { fg = c.white_1, style = "bold" },
		LspSagaCodeActionTitle = { fg = c.yellow, style = "bold" },
		LspSagaCodeActionContent = { fg = c.green, style = "bold" },
		LspFloatWinNormal = { fg = c.fg, bg = c.black_1 },
		LspDiagnosticsFloatingError = { fg = c.red_1 },
		LspDiagnosticsFloatingWarn = { fg = c.orange_1 },
		LspDiagnosticsFloatingInfor = { fg = c.white_2 },
		LspDiagnosticsFloatingHint = { fg = c.yellow_1 },
		LspSagaDiagnosticHeader = { fg = c.yellow },
		LspSagaBorderTitle = { fg = c.yellow, style = "bold" },
		DiagnosticInformation = { fg = c.yellow, style = "bold" },

		-- CMP
		CmpItemAbbrMatch = { fg = c.blue_3 },
		CmpItemAbbrMatchFuzzy = { fg = c.blue_3},
		CmpItemKindVariable = {fg = c.light_blue},
		CmpItemKindInterface = {fg = c.light_blue},
		CmpItemKindText = {fg = c.light_blue},
		CmpItemKindFunction = {fg = c.purple},
		CmpItemKindMethod = {fg = c.purple},
		CmpItemKindKeyword = {fg = c.white_3},
		CmpItemKindProperty = {fg = c.white_3},
		CmpItemKindUnit = {fg = c.purple},
  }

  for group, parameters in pairs(groups) do
    utils.highlight(group, parameters)
  end
end

M.colorscheme = function()
  vim.api.nvim_command("hi clear")
  if vim.fn.exists("syntax_on") then
    vim.api.nvim_command("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "astron"

  set_groups()
end

return M