local conf = require("astron.config").config

local treesitter = {

  -- Italics stuff
  TSComment = { fg = C.grey_2, bg = C.none, style = conf.comment_style },
  TSBoolean = { fg = C.orange, bg = C.none, style = conf.boolean_style },
  TSConditional = { fg = C.purple, bg = C.none, style = conf.keyword_style },
  TSKeyword = { fg = C.purple, bg = C.none, style = conf.keyword_style },
  TSKeywordReturn = { fg = C.purple, style = conf.keyword_style },
  TSRepeat = { fg = C.purple, bg = C.none, style = conf.keyword_style },
  TSFunction = { fg = C.blue, bg = C.none, style = conf.function_style },
  TSKeywordFunction = { fg = C.blue, bg = C.none, conf.function_style },
  TSFuncBuiltin = { fg = C.blue, bg = C.bgnone, style = conf.function_style },
  TSMethod = { fg = C.blue, bg = C.none, style = conf.function_style },

  -- Basic stuff
  TSError = { fg = C.red, bg = C.none },
  TSPunctDelimiter = { fg = C.fg, bg = C.none },
  TSPunctBracket = { fg = C.fg, bg = C.none },
  TSPunctSpecial = { fg = C.fg, bg = C.none },
  TSConstant = { fg = C.yellow, bg = C.none },
  TSConstBuiltin = { fg = C.orange, bg = C.none },
  TSConstMacro = { fg = C.red, bg = C.none },
  TSStringRegex = { fg = C.green, bg = C.none },
  TSString = { fg = C.green, bg = C.none },
  TSStringEscap = { fg = C.red, bg = C.none },
  TSCharacter = { fg = C.green, bg = C.none },
  TSNumber = { fg = C.orange, bg = C.none },
  TSFloat = { fg = C.green, bg = C.none },
  TSAnnotation = { fg = C.yellow, bg = C.none },
  TSAttribute = { fg = C.red, bg = C.none },
  TSNamespace = { fg = C.purple, bg = C.none },
  TSFuncMacro = { fg = C.yellow, bg = C.none },
  TSParameter = { fg = C.red, bg = C.none },
  TSParameterReference = { fg = C.cyan, bg = C.none },
  TSField = { fg = C.red, bg = C.none },
  TSProperty = { fg = C.yellow, bg = C.none },
  TSConstructor = { fg = C.yellow, bg = C.none },
  TSLabel = { fg = C.blue, bg = C.none },
  TSKeywordOperator = { fg = C.purple, bg = C.none },
  TSOperator = { fg = C.cyan, bg = C.none },
  TSException = { fg = C.purple, bg = C.none },
  TSType = { fg = C.blue, bg = C.none },
  TSTypeBuiltin = { fg = C.blue, bg = C.none },
  TSStructure = { fg = C.purple, bg = C.none },
  TSInclude = { fg = C.purple, bg = C.none },
  TSVariable = { fg = C.red, bg = C.none, style = conf.variable_style },
  TSVariableBuiltin = { fg = C.yellow, bg = C.none, style = conf.variable_style },
  TSText = { fg = C.fg, bg = C.none },
  TSStrong = { fg = C.fg, bg = C.none },
  TSEmphasis = { fg = C.fg, bg = C.none },
  TSUnderline = { fg = C.fg, bg = C.none },
  TSTitle = { fg = C.fg, bg = C.none },
  TSLiteral = { fg = C.fg, bg = C.none },
  TSURI = { fg = C.fg, bg = C.none },
  TSTag = { fg = C.red, bg = C.none },
  TSTagDelimiter = { fg = C.fg, bg = C.none },
  rainbowcol1 = { fg = "Gold", bg = C.none },
  rainbowcol2 = { fg = "Orchid", bg = C.none },
  rainbowcol3 = { fg = "LightSkyBlue", bg = C.none },
  rainbowcol4 = { fg = "Gold", bg = C.none },
  rainbowcol5 = { fg = "Orchid", bg = C.none },
  rainbowcol6 = { fg = "LightSkyBlue", bg = C.none },
  rainbowcol7 = { fg = "Orchid", bg = C.none },
}

return treesitter
